//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENDI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUYENDI()
        {
            this.HINHANH_CHUYENDI = new HashSet<HINHANH_CHUYENDI>();
            this.LOTRINH = new HashSet<LOTRINH>();
            this.THAMGIA = new HashSet<THAMGIA>();
        }
    
        public string MA_CHUYENDI { get; set; }
        public string TEN_CHUYENDI { get; set; }
        public string DIEMDEN { get; set; }
        public Nullable<bool> TRANGTHAI { get; set; }
        public Nullable<double> THUE_XE { get; set; }
        public Nullable<double> THUE_KS { get; set; }
        public Nullable<double> MAYBAY { get; set; }
        public Nullable<System.DateTime> NGAYDI { get; set; }
        public Nullable<System.DateTime> NGAYVE { get; set; }
    
        public virtual DD_DULICH DD_DULICH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANH_CHUYENDI> HINHANH_CHUYENDI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOTRINH> LOTRINH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THAMGIA> THAMGIA { get; set; }
    }
}
