//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbWeSplitEntities : DbContext
    {
        public dbWeSplitEntities()
            : base("name=dbWeSplitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHUYENDI> CHUYENDI { get; set; }
        public virtual DbSet<DD_DULICH> DD_DULICH { get; set; }
        public virtual DbSet<DD_DUNGCHAN> DD_DUNGCHAN { get; set; }
        public virtual DbSet<HINHANH_CHUYENDI> HINHANH_CHUYENDI { get; set; }
        public virtual DbSet<KHOANCHI> KHOANCHI { get; set; }
        public virtual DbSet<LOTRINH> LOTRINH { get; set; }
        public virtual DbSet<THAMGIA> THAMGIA { get; set; }
        public virtual DbSet<THANHVIEN> THANHVIEN { get; set; }
    }
}
