//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANH_CHUYENDI
    {
        public string MA_ANH_CD { get; set; }
        public string TENANH_CD { get; set; }
        public string CHUYENDI { get; set; }
    
        public virtual CHUYENDI CHUYENDI1 { get; set; }
    }
}
