//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOANCHI
    {
        public string MA_KCHI { get; set; }
        public string MA_CHUYENDI { get; set; }
        public string MA_DD_DUNGCHAN { get; set; }
        public Nullable<int> STT_DC { get; set; }
        public string HANGMUC { get; set; }
        public Nullable<double> SOTIENCHI { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual LOTRINH LOTRINH { get; set; }
    }
}
