//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOTRINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOTRINH()
        {
            this.KHOANCHI = new HashSet<KHOANCHI>();
        }
    
        public int STT { get; set; }
        public string MA_CHUYENDI { get; set; }
        public string MA_DD_DUNGCHAN { get; set; }
        public string DD_DUNGCHAN { get; set; }
        public string MOTA { get; set; }
    
        public virtual CHUYENDI CHUYENDI { get; set; }
        public virtual DD_DUNGCHAN DD_DUNGCHAN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHOANCHI> KHOANCHI { get; set; }
    }
}
