//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMGIA
    {
        public string MACD { get; set; }
        public string MATV { get; set; }
        public Nullable<double> TIENTHU { get; set; }
    
        public virtual CHUYENDI CHUYENDI { get; set; }
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}
